### ISSUE TITLE
Cannot create pipelines

### ISSUE THREAD

**Issue by stjohnjohnson** [screwdriver-cd/api#29]
Unable to create a new pipeline.

```bash
sd$ pipeline create git@github.com:screwdriver-cd/api.git#master
Ooops { statusCode: 500,
  error: 'Internal Server Error',
  message: 'An internal server error occurred' }
```

```
160721/060003.052, [error] message: Uncaught error: Cannot read property 'id' of undefined stack: TypeError: Uncaught error: Cannot read property 'id' of undefined
    at Pipeline.create (/Users/stjohn/Sites/Screwdriver/api/node_modules/screwdriver-plugin-pipelines/lib/create.js:38:60)
    at MyDatastore.save (/Users/stjohn/Sites/Screwdriver/api/node_modules/screwdriver-datastore-imdb/index.js:63:9)
    at get (/Users/stjohn/Sites/Screwdriver/api/node_modules/screwdriver-models/lib/pipeline.js:50:35)
    at MyDatastore.get (/Users/stjohn/Sites/Screwdriver/api/node_modules/screwdriver-datastore-imdb/index.js:48:9)
    at PipelineModel.get (/Users/stjohn/Sites/Screwdriver/api/node_modules/screwdriver-models/lib/base.js:27:31)
    at PipelineModel.create (/Users/stjohn/Sites/Screwdriver/api/node_modules/screwdriver-models/lib/pipeline.js:30:14)
    at Pipeline.get (/Users/stjohn/Sites/Screwdriver/api/node_modules/screwdriver-plugin-pipelines/lib/create.js:29:26)
    at MyDatastore.get (/Users/stjohn/Sites/Screwdriver/api/node_modules/screwdriver-datastore-imdb/index.js:48:9)
    at PipelineModel.get (/Users/stjohn/Sites/Screwdriver/api/node_modules/screwdriver-models/lib/base.js:27:31)
    at config.handler (/Users/stjohn/Sites/Screwdriver/api/node_modules/screwdriver-plugin-pipelines/lib/create.js:21:22)
```

**Comment by stjohnjohnson** [comment]
Interestingly enough, it created the entry.

```
pipeline list
[
    {
        "createTime": 1469080803068,
        "platform": "generic@1",
        "configUrl": "git@github.com:screwdriver-cd/api.git#master",
        "scmUrl": "git@github.com:screwdriver-cd/api.git#master",
        "id": "b74a1200071190982aeb37dc0d71b8e5b171bf35"
    }
]
```

**Comment by d2lam** [comment]
Yeah I rebuilt the docker image earlier today. It's using the new data-schema and the old data we had there do not conform anymore. A lot of things are not broken so we need to fix this tomorrow in order to verify the refactoring stories and some bug fixing stories.

**Comment by d2lam** [comment]
Just took a look at the code. This particular bug probably comes from here:
https://github.com/screwdriver-cd/plugin-pipelines/blob/master/lib/create.js#L40

Pipeline.create only returns callback(err). `result.id` does not exist. That line should be 
```
pathname: `${request.path}/${pipelineId}`
```

**Comment by d2lam** [comment]
@stjohnjohnson  Can you try again?

**Comment by stjohnjohnson** [comment]
Works, but no jobs are created :(

**Comment by d2lam** [comment]
Yeah. Fixing that now, since we added sync, we need to call that inside plugin-pipeline to create the main job.
